apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # пароль "password", закодований в base64
  mysql-database: ZGF0YWJhc2U= # назва бази "database", закодований в base64
  mysql-user: dXNlcg== # ім'я користувача "user", закодований в base64
  mysql-password: cGFzc3dvcmQ= # пароль "password", закодований в base64
