name: MySQL Docker Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Резервне копіювання щодня о 2:00
  workflow_dispatch:  # Можливість ручного запуску

jobs:
  backup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker-compose up -d

      - name: Run Backup Script
        run: ./backup.sh

      - name: Commit and Push Backup
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "your-email@example.com"
          git add backups/
          git commit -m "Database backup - $(date)"
          git push origin main
